routes/web.php
<?php

use App\Http\Controllers\EmployeeController;
use App\Http\Controllers\ProfileController;
use App\Http\Controllers\CompanyController;
use App\Models\Company;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get('/dashboard', function () {
    return view('dashboard');
})->middleware(['auth', 'verified'])->name('dashboard');

Route::middleware('auth')->group(function () {
    Route::get('/profile', [ProfileController::class, 'edit'])->name('profile.edit');
    Route::patch('/profile', [ProfileController::class, 'update'])->name('profile.update');
    Route::delete('/profile', [ProfileController::class, 'destroy'])->name('profile.destroy');
    Route::resource('/companies', CompanyController::class);
    Route::resource('/employees', EmployeeController::class);
});

require __DIR__.'/auth.php';

app/View/Components/AppLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;
use Illuminate\View\View;

class AppLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     */
    public function render(): View
    {
        return view('layouts.app');
    }
}

resources/views/сompanies/create.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 dark:text-gray-200 leading-tight">
            {{ __('Компании') }}
        </h2>
    </x-slot>

    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white dark:bg-gray-800 overflow-hidden shadow-sm sm:rounded-lg">
                <div class="p-6 text-gray-900 dark:text-gray-100">

                @if ($errors->any())
                <div class="alert alert-danger">
                    <ul>
                        @foreach ($errors->all() as $error)
                            <li>{{ $error }}</li>
                        @endforeach
                    </ul>
                </div>
                @endif
                    

        <h3 class="mb-5 text-center">Добавление новой компании</h3>
        <form class="row g-3" method="post" action="{{route('companies.store')}}" enctype="multipart/form-data">
        @csrf
          <div class="col-md-6">
            <input type="text" class="form-control {{ $errors->has('name') ? ' is-invalid' : '' }}" id="inputName" name="name" aria-describedy="name" placeholder="Название" required value="{{ old('name') }}">
          </div>
          <div class="col-md-6">
            <input type="text" class="form-control {{ $errors->has('email') ? ' is-invalid' : '' }}" id="inputEmail" name="email" aria-describedy="email" placeholder="Email" value="{{ old('email') }}">
          </div>
          <div class="col-md-6">
            <input type="file" class="form-control" id="inputLogo" name="logo" aria-describedy="logo" placeholder="Путь к картинке">
          </div>
          <div class="col-md-6">
            <input type="text" class="form-control {{ $errors->has('website') ? ' is-invalid' : '' }}" id="inputWebsite" name="website" aria-describedy="website" placeholder="Сайт" value="{{ old('website') }}">
          </div>
          <div class="col-12 text-center mt-5">
            <button type="submit" class="btn btn-outline-success">Добавить</button>
          </div>
        </form>

                </div>
            </div>
        </div>
    </div>
</x-app-layout>

resources/views/сompanies/edit.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 dark:text-gray-200 leading-tight">
            {{ __('Компании') }}
        </h2>
    </x-slot>

    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white dark:bg-gray-800 overflow-hidden shadow-sm sm:rounded-lg">
                <div class="p-6 text-gray-900 dark:text-gray-100">
                    
                    @if ($errors->any())
                    <div class="alert alert-danger">
                        <ul>
                            @foreach ($errors->all() as $error)
                                <li>{{ $error }}</li>
                            @endforeach
                        </ul>
                    </div>
                    @endif

                            <h3 class="mb-5 text-center">Измение данных о компании</h3>
                            <form class="row g-3" method="post" action="{{route('companies.update', $company)}}" enctype="multipart/form-data">
                            @csrf
                            @method('PUT')
                            <div class="col-md-6">
                                <input type="text" class="form-control" id="inputName" name="name" aria-describedy="name" placeholder="Название" value="{{$company->name}}">
                            </div>
                            <div class="col-md-6">
                                <input type="text" class="form-control" id="inputEmail" name="email" aria-describedy="email" placeholder="Email" value="{{$company->email}}">
                            </div>
                            <div class="col-md-6">
                                <img src="/img/{{$company->logo}}" alt="logo" width="100" height="100">
                                <input type="file" class="form-control" id="inputLogo" name="logo" aria-describedy="logo" enctype="multipart/form-data" placeholder="Путь к картинке">
                            </div>
                            <div class="col-md-6">
                                <input type="text" class="form-control" id="inputWebsite" name="website" aria-describedy="website" placeholder="Сайт" value="{{$company->website}}">
                            </div>
                            <div class="col-12 text-center mt-5">
                                <button type="submit" class="btn btn-outline-success">Обновить</button>
                            </div>
                            </form>

                </div>
            </div>
        </div>
    </div>
</x-app-layout>

resources/views/сompanies/index.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 dark:text-gray-200 leading-tight">
            {{ __('Компании') }}
        </h2>
    </x-slot>

    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white dark:bg-gray-800 overflow-hidden shadow-sm sm:rounded-lg">
                <div class="p-6 text-gray-900 dark:text-gray-100">
                    

                    <a class="btn btn-success mb-3" href="{{route('companies.create')}}" role="button">Добавить новую компанию</a>

                        <table class="table table-bordered">
                        <thead>
                            <tr>
                            <th scope="col">Имя</th>
                            <th scope="col">Логотип</th>
                            <th scope="col">Сайт</th>
                            <th scope="col">Email</th>
                            <th scope="col"></th>
                            </tr>
                        </thead>
                        <tbody>
                        @foreach ($сompanies as $company)
                            <tr>
                            <th>{{$company->name}}</th>
                            <td>
                            <img src="/img/{{$company->logo}}" height="100" width="100">
                            </td>
                            <td>{{$company->website}}</td>
                            <td>{{$company->email}}</td>
                            <td>
                            <a class="btn btn-light mb-1" href="{{route('companies.edit', $company)}}" role="button">Изменить</a>
                            <br />
                            <form method="POST" action="{{route('companies.destroy', $company)}}">
                                    @csrf
                                    @method('DELETE')
                                    <button class="btn btn-outline-danger" type="submit">Удалить</button>
                            </form>
                            </td>
                            </tr>
                            @endforeach
                        </tbody>
                        </table>

                        <div>
                            {{ $сompanies->links() }}
                        </div>

                </div>
            </div>
        </div>
    </div>
</x-app-layout>