routes/web.php
<?php

use App\Http\Controllers\EmployeeController;
use App\Http\Controllers\ProfileController;
use App\Http\Controllers\CompanyController;
use App\Models\Company;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get('/dashboard', function () {
    return view('dashboard');
})->middleware(['auth', 'verified'])->name('dashboard');

Route::middleware('auth')->group(function () {
    Route::get('/profile', [ProfileController::class, 'edit'])->name('profile.edit');
    Route::patch('/profile', [ProfileController::class, 'update'])->name('profile.update');
    Route::delete('/profile', [ProfileController::class, 'destroy'])->name('profile.destroy');
    Route::resource('/companies', CompanyController::class);
    Route::resource('/employees', EmployeeController::class);
});

require __DIR__.'/auth.php';

app/Models/Employee.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Employee extends Model
{
    use HasFactory;
    protected $guarded = [];

    public function companies()
    {
        return $this->belongsTo(Company::class, 'company');
    }
}

app/Http/Controllers/Api/EmployeeController.php
<?php

namespace App\Http\Controllers\Api;

use App\Http\Controllers\Controller;
use App\Models\Employee;
use Illuminate\Http\Request;

class EmployeeController extends Controller
{
    /**
     * Display a listing of the resource.
     */
    public function index()
    {
        return Employee::all();
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     */
    public function show(string $id)
    {
        return Employee::find($id);
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(Request $request, string $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(string $id)
    {
        //
    }
}

app/Http/Controllers/EmployeeController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\EmployeesStoreRequest;
use App\Models\Company;
use App\Models\Employee;
use Illuminate\Http\Request;
use Illuminate\Http\RedirectResponse;

class EmployeeController extends Controller
{
    /**
     * Display a listing of the resource.
     */
    public function index()
    {
        $employees = Employee::with(['companies'])->orderBy('name')->paginate(5);
        
        return view('employees.index', ['employees'=>$employees]);
    }

    /**
     * Show the form for creating a new resource.
     */
    public function create()
    {
        return view('employees.create', ['companies'=>Company::all()]);
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(EmployeesStoreRequest $request)
    {

        Employee::create([
        'name'=>$request->name,
        'surname'=>$request->surname,
        'company'=>$request->company,
        'email'=>$request->email,
        'phone'=>$request->phone,
        ]);

        return redirect('employees')->with('info', 'Товар добавлен');
    }

    /**
     * Display the specified resource.
     */
    public function show(string $id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit(Employee $employee)
    {
        return view('employees.edit', ['employee'=>$employee, 'companies'=>Company::all()]);
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(EmployeesStoreRequest $request, Employee $employee)
    {
        $employee->name = $request->name;
        $employee->surname = $request->surname;
        $employee->company = $request->company;
        $employee->email = $request->email;
        $employee->phone = $request->phone;
        $employee->save();

        return redirect('employees');
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(Employee $employee)
    {
        $employee->delete();
        return redirect('employees');
    }
}

app/View/Components/AppLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;
use Illuminate\View\View;

class AppLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     */
    public function render(): View
    {
        return view('layouts.app');
    }
}

resources/views/employees/create.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 dark:text-gray-200 leading-tight">
            {{ __('Сотрудники') }}
        </h2>
    </x-slot>

    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white dark:bg-gray-800 overflow-hidden shadow-sm sm:rounded-lg">
                <div class="p-6 text-gray-900 dark:text-gray-100">
            
                        @if ($errors->any())
                        <div class="alert alert-danger">
                            <ul>
                                @foreach ($errors->all() as $error)
                                    <li>{{ $error }}</li>
                                @endforeach
                            </ul>
                        </div>
                        @endif

                    <h3 class="mb-5 text-center">Добавление нового сотрудника</h3>
                    <form class="row g-3" method="post" action="{{route('employees.store')}}" enctype="multipart/form-data">
                    @csrf
                    <div class="col-md-6">
                        <input type="text" class="form-control {{ $errors->has('name') ? ' is-invalid' : '' }}" id="inputName" name="name" aria-describedy="name" placeholder="Имя" value="{{ old('name') }}" required>
                    </div>
                    <div class="col-md-6">
                        <input type="text" class="form-control {{ $errors->has('surname') ? ' is-invalid' : '' }}" id="inputSurname" name="surname" aria-describedy="surname" placeholder="Фамилия" value="{{ old('surname') }}" required>
                    </div>
                    <div class="col-md-6">
                        <select class="form-select" aria-label="Кампания" name="company">
                        @foreach ($companies as $company)
                            <option value="{{$company->id}}">{{$company->name}}</option>
                        @endforeach
                        </select>
                    </div>
                    <div class="col-md-6">
                    <input type="text" class="form-control {{ $errors->has('email') ? ' is-invalid' : '' }}" id="inputEmail" name="email" aria-describedy="email" placeholder="Email" value="{{ old('email') }}">
                    </div>
                    <div class="col-md-6">
                    <input type="text" class="form-control {{ $errors->has('phone') ? ' is-invalid' : '' }}" id="inputPhone" name="phone" aria-describedy="phone" placeholder="Телефон" value="{{ old('phone') }}">
                    </div>
                    <div class="col-12 text-center mt-5">
                        <button type="submit" class="btn btn-outline-success">Добавить</button>
                    </div>
                    </form>

                </div>
            </div>
        </div>
    </div>
</x-app-layout>

resources/views/employees/edit.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 dark:text-gray-200 leading-tight">
            {{ __('Сотрудники') }}
        </h2>
    </x-slot>

    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white dark:bg-gray-800 overflow-hidden shadow-sm sm:rounded-lg">
                <div class="p-6 text-gray-900 dark:text-gray-100">
                    

                            @if ($errors->any())
                            <div class="alert alert-danger">
                                <ul>
                                    @foreach ($errors->all() as $error)
                                        <li>{{ $error }}</li>
                                    @endforeach
                                </ul>
                            </div>
                            @endif

                            <h3 class="mb-5 text-center">Измение данных о сотруднике</h3>
                            <form class="row g-3" method="post" action="{{route('employees.update', $employee)}}" enctype="multipart/form-data">
                            @csrf
                            @method('PUT')
                            <div class="col-md-6">
                                <input type="text" class="form-control" id="inputName" name="name" aria-describedy="name" placeholder="Имя" value="{{$employee->name}}">
                            </div>
                            <div class="col-md-6">
                                <input type="text" class="form-control" id="inputSurname" name="surname" aria-describedy="surname" placeholder="Фамилия" value="{{$employee->surname}}">
                            </div>
                            <div class="col-md-6">
                                <select class="form-select" aria-label="Категория товара" name="company">
                                @foreach ($companies as $company)
                                    <option value="{{$company->id}}" 
                                    @if ($company->id == $employee->company)
                                        selected
                                    @endif>
                                    {{$company->name}}</option>
                                @endforeach
                                </select>
                            </div>
                            <div class="col-md-6">
                                <input type="text" class="form-control" id="inputEmail" name="email" aria-describedy="email" placeholder="Email" value="{{$employee->email}}">
                            </div>
                            <div class="col-md-6">
                                <input type="text" class="form-control" id="inputPhone" name="phone" aria-describedy="phone" placeholder="Телефон" value="{{$employee->phone}}">
                            </div>
                            <div class="col-12 text-center mt-5">
                                <button type="submit" class="btn btn-outline-success">Обновить</button>
                            </div>
                            </form>

                </div>
            </div>
        </div>
    </div>
</x-app-layout>

resources/views/employees/index.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 dark:text-gray-200 leading-tight">
            {{ __('Сотрудники') }}
        </h2>
    </x-slot>

    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white dark:bg-gray-800 overflow-hidden shadow-sm sm:rounded-lg">
                <div class="p-6 text-gray-900 dark:text-gray-100">
                    

                    <a class="btn btn-success mb-3" href="{{route('employees.create')}}" role="button">Добавить нового сотрудника</a>

                    <table class="table table-bordered">
                        <thead>
                            <tr>
                            <th scope="col">Имя</th>
                            <th scope="col">Фамилия</th>
                            <th scope="col">Компания</th>
                            <th scope="col">Email</th>
                            <th scope="col">Телефон</th>
                            <th scope="col"></th>
                            </tr>
                        </thead>
                        <tbody>
                        @foreach ($employees as $employee)
                            <tr>
                            <td>{{$employee->name}}</td>
                            <td>{{$employee->surname}}</td>
                            <td>{{$employee->companies->name}}</td>
                            <td>{{$employee->email}}</td>
                            <td>{{$employee->phone}}</td>
                            <td>
                            <a class="btn btn-light mb-1" href="{{route('employees.edit', $employee)}}" role="button">Изменить</a>
                            <br />
                            <form method="POST" action="{{route('employees.destroy', $employee)}}">
                                    @csrf
                                    @method('DELETE')
                                    <button class="btn btn-outline-danger" type="submit">Удалить</button>
                            </form>
                            </td>
                            </tr>
                            @endforeach
                        </tbody>
                        </table>

                        <div>
                            {{ $employees->links() }}
                        </div>

                </div>
            </div>
        </div>
    </div>
</x-app-layout>